apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-discovery
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-discovery
  template:
    metadata:
      labels:
        app: workload-discovery
    spec:
      serviceAccountName: workload-discovery-sa
      containers:
      - name: workload-discovery
        image: workload-discovery:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"