apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-discovery-sa
  namespace: image-type-discovery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workload-discovery-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workload-discovery-binding
subjects:
- kind: ServiceAccount
  name: workload-discovery-sa
  namespace: image-type-discovery
roleRef:
  kind: ClusterRole
  name: workload-discovery-role
  apiGroup: rbac.authorization.k8s.io