apiVersion: v1
kind: Service
metadata:
  name: workload-discovery
  namespace: image-type-discovery
  labels:
    app: workload-discovery
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: workload-discovery